### ISSUE TITLE
problems with bc2rg.py

### ISSUE THREAD

**Issue by leomorelli** [dawe/scatACC#2]
When I run this code:
`python ~/scatACC/bc2rg.py -w fastaq/manual_umi/prova_whitelist.tsv -i fastaq/manual_test_results_1a/8_7w_scGETseq_BC_TAAGGCGA_READ2.fq -b 8_7w_scGETseq_BC_TAAGGCGA.bam -O -k -G 8_7w_scGETseq_tn5_TAAGGCGA`

The following error occurs:

> Traceback (most recent call last):
  File "/home/morelli/scatACC/bc2rg.py", line 114, in <module>
    main()
  File "/home/morelli/scatACC/bc2rg.py", line 90, in main
    header = build_header(bam_in.header, coder, options.group, options.keep_unmatched)
  File "/home/morelli/scatACC/bc2rg.py", line 49, in build_header
    _pl = in_header['RG'][0]['PL']
KeyError: 'PL'

Files are obtained as follows:

-  _whitelist.tsv is obtained with 'umi_tools withelist'
- _READ2.fq is obtained through 'tagdust'
-  the BAM file is obtained with 'bwa_mem' | 'sam_tools' sort

**Comment by dawe** [comment]
It seems that the "PL" field is not in the BAM header. Could you check this:

`samtools view -H 8_7w_scGETseq_BC_TAAGGCGA.bam | grep '@RG'  | head`

I will add a check for different fields in the header

**Comment by leomorelli** [comment]
My fault, I did not specify the platform in the BAM header.
Thank you!
